"""products

Revision ID: 001_products
Revises: 
Create Date: 2026-09-19 13:38:53.653140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_products'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # PART 1, generated by Alembic (`--autogenerate`): it compared Base.metadata with the
    # empty database and wrote the table, both CHECK constraints and the category index.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_cents >= 0', name='ck_products_price_cents'),
    sa.CheckConstraint('stock >= 0', name='ck_products_stock'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###

    # PART 2, added BY HAND: the seed data. Autogenerate compares schemas, not data, so it
    # can never write this. The ids are assigned by the IDENTITY column in insertion order
    # (1..36); the image URL uses the same number so every product gets its own picture.
    # Categories rotate (laptops, monitors, peripherals, storage, networking) so every page
    # of the catalog shows a mix. Products 2, 15, 23 and 34 are out of stock on purpose.
    op.execute("""
        INSERT INTO products (name, description, category, price_cents, stock, image_url) VALUES
        ('ProBook 14 Laptop', '14-inch business laptop, 16 GB RAM, 512 GB SSD, 10-hour battery.', 'laptops', 89900, 12, 'https://picsum.photos/seed/product-1/400/300'),
        ('27" Monitor', '27-inch Full HD IPS monitor with thin bezels.', 'monitors', 24900, 0, 'https://picsum.photos/seed/product-2/400/300'),
        ('Wireless Mouse', 'Ergonomic wireless mouse with a 12-month battery.', 'peripherals', 2999, 40, 'https://picsum.photos/seed/product-3/400/300'),
        ('500 GB NVMe SSD', 'M.2 NVMe drive, up to 3,500 MB/s read speed.', 'storage', 5999, 50, 'https://picsum.photos/seed/product-4/400/300'),
        ('Wi-Fi 6 Router', 'Dual-band Wi-Fi 6 router with four gigabit ports.', 'networking', 8999, 25, 'https://picsum.photos/seed/product-5/400/300'),
        ('UltraSlim 13 Laptop', '13-inch ultraportable, 1.1 kg, 16 GB RAM, 1 TB SSD.', 'laptops', 109900, 8, 'https://picsum.photos/seed/product-6/400/300'),
        ('24" Full HD Monitor', '24-inch IPS panel, 75 Hz, HDMI and DisplayPort inputs.', 'monitors', 13900, 20, 'https://picsum.photos/seed/product-7/400/300'),
        ('Mechanical Keyboard', 'Tenkeyless mechanical keyboard with tactile switches.', 'peripherals', 8999, 22, 'https://picsum.photos/seed/product-8/400/300'),
        ('1 TB NVMe SSD', 'M.2 NVMe drive, up to 5,000 MB/s read speed.', 'storage', 9999, 40, 'https://picsum.photos/seed/product-9/400/300'),
        ('8-Port Gigabit Switch', 'Unmanaged desktop switch, eight gigabit ports, fanless.', 'networking', 3999, 30, 'https://picsum.photos/seed/product-10/400/300'),
        ('WorkStation 16 Laptop', '16-inch workstation, 64 GB RAM, dedicated GPU, 2 TB SSD.', 'laptops', 149900, 3, 'https://picsum.photos/seed/product-11/400/300'),
        ('32" 4K Monitor', '32-inch 4K UHD monitor with USB-C charging.', 'monitors', 42900, 9, 'https://picsum.photos/seed/product-12/400/300'),
        ('Webcam 1080p', 'Full HD webcam with autofocus and a privacy shutter.', 'peripherals', 4999, 17, 'https://picsum.photos/seed/product-13/400/300'),
        ('2 TB NVMe SSD', 'M.2 NVMe drive with a heatsink, up to 7,000 MB/s.', 'storage', 17900, 15, 'https://picsum.photos/seed/product-14/400/300'),
        ('Mesh Wi-Fi System (2 pack)', 'Two-node mesh system that covers up to 300 square metres.', 'networking', 17900, 0, 'https://picsum.photos/seed/product-15/400/300'),
        ('StudentBook 15 Laptop', '15-inch everyday laptop, 8 GB RAM, 256 GB SSD.', 'laptops', 44900, 25, 'https://picsum.photos/seed/product-16/400/300'),
        ('34" Ultrawide Monitor', '34-inch curved ultrawide monitor, 3440 x 1440 resolution.', 'monitors', 47900, 6, 'https://picsum.photos/seed/product-17/400/300'),
        ('USB-C Docking Station', 'Dual-display dock with Ethernet and 100 W power passthrough.', 'peripherals', 12900, 9, 'https://picsum.photos/seed/product-18/400/300'),
        ('1 TB Portable SSD', 'Pocket-sized USB-C external SSD, up to 1,000 MB/s.', 'storage', 10900, 28, 'https://picsum.photos/seed/product-19/400/300'),
        ('Cat6 Ethernet Cable 2 m', 'Shielded Cat6 patch cable, two metres, snagless connectors.', 'networking', 999, 200, 'https://picsum.photos/seed/product-20/400/300'),
        ('GameForce 17 Laptop', '17-inch gaming laptop, 165 Hz screen, dedicated GPU.', 'laptops', 129900, 5, 'https://picsum.photos/seed/product-21/400/300'),
        ('27" 4K Monitor', '27-inch 4K IPS monitor with factory colour calibration.', 'monitors', 36900, 11, 'https://picsum.photos/seed/product-22/400/300'),
        ('Noise-Cancelling Headset', 'Over-ear wireless headset with a detachable microphone.', 'peripherals', 15900, 0, 'https://picsum.photos/seed/product-23/400/300'),
        ('2 TB External Hard Drive', 'USB 3.0 external hard drive in a rugged case.', 'storage', 6499, 30, 'https://picsum.photos/seed/product-24/400/300'),
        ('Wi-Fi 6 USB Adapter', 'Dual-band USB 3.0 Wi-Fi 6 adapter for desktops and laptops.', 'networking', 2499, 45, 'https://picsum.photos/seed/product-25/400/300'),
        ('TravelBook 11 Laptop', '11-inch compact laptop, fanless, 12-hour battery.', 'laptops', 32900, 18, 'https://picsum.photos/seed/product-26/400/300'),
        ('22" Office Monitor', '22-inch Full HD monitor for the office, VESA mount ready.', 'monitors', 9999, 22, 'https://picsum.photos/seed/product-27/400/300'),
        ('Laptop Stand', 'Foldable aluminium stand with adjustable height.', 'peripherals', 3999, 35, 'https://picsum.photos/seed/product-28/400/300'),
        ('128 GB USB Flash Drive', 'USB 3.2 flash drive with a retractable connector.', 'storage', 1499, 100, 'https://picsum.photos/seed/product-29/400/300'),
        ('Powerline Adapter Kit', 'Pair of adapters that carry the network over the mains wiring.', 'networking', 5999, 18, 'https://picsum.photos/seed/product-30/400/300'),
        ('CreatorBook 16 Laptop', '16-inch laptop with a colour-accurate OLED screen.', 'laptops', 139900, 4, 'https://picsum.photos/seed/product-31/400/300'),
        ('Portable 15" Monitor', '15.6-inch USB-C portable monitor, 700 g.', 'monitors', 17900, 13, 'https://picsum.photos/seed/product-32/400/300'),
        ('Graphics Tablet', 'Drawing tablet with a 10 x 6 inch active area and a battery-free pen.', 'peripherals', 6999, 12, 'https://picsum.photos/seed/product-33/400/300'),
        ('4 TB NAS Hard Drive', 'Hard drive built for 24/7 use in a network storage box.', 'storage', 12900, 0, 'https://picsum.photos/seed/product-34/400/300'),
        ('24-Port Managed Switch', 'Rack-mount managed switch with VLAN support.', 'networking', 24900, 7, 'https://picsum.photos/seed/product-35/400/300'),
        ('OfficeBook 15 Laptop', '15-inch office laptop with a full-size keyboard and numpad.', 'laptops', 54900, 14, 'https://picsum.photos/seed/product-36/400/300')
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Generated by Alembic. Nothing to add by hand: dropping the table also removes the
    # seed rows, so the downgrade leaves the database exactly as it was before.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
