"""categories expand

Revision ID: 001c_categories_expand
Revises: 001b_product_images_jpg
Create Date: 2026-09-19 16:08:21.236688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001c_categories_expand'
down_revision: Union[str, Sequence[str], None] = '001b_product_images_jpg'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and data."""
    # EXPAND, the first half of expand-contract. Nothing here breaks code that is already
    # running: the new table is new, and the new column is NULLABLE, so an INSERT written
    # before this migration still works. Both ways of naming the category live side by side
    # until the CONTRACT step (001d) removes the old one.
    #
    # PART 1, generated by Alembic: the table, the column, its index and the foreign key.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_foreign_key('fk_products_category_id', 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###

    # PART 2, added BY HAND: moving the data. Autogenerate compares schemas, not data, so it
    # created an empty table and a column full of NULLs and stopped there.
    # One row per distinct name already in products: the categories are not a list written
    # here, they are read from the data itself, so nothing can be missed or invented.
    # ORDER BY so the ids come out the same on every machine: without it the order is
    # whatever the database finds convenient, and a demo would show different ids each time.
    op.execute("INSERT INTO categories (name) SELECT DISTINCT category FROM products ORDER BY 1")

    # And now every product points at its own category. After this, the two columns say the
    # same thing, which is the whole point of EXPAND: the change can be checked and, if it
    # were wrong, undone, while the application keeps reading the old column.
    op.execute("""
        UPDATE products
        SET category_id = categories.id
        FROM categories
        WHERE categories.name = products.category
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Generated by Alembic. Nothing to add by hand: the data that was copied lives in the
    # column and the table that these commands remove, and the old text column was never
    # touched, so it is still the source of truth.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_category_id', 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_column('products', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
