"""categories contract

Revision ID: 001d_categories_contract
Revises: 001c_categories_expand
Create Date: 2026-09-19 16:09:31.458285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001d_categories_contract'
down_revision: Union[str, Sequence[str], None] = '001c_categories_expand'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # CONTRACT, the second half of expand-contract, and the half that DOES break old code:
    # anything still reading products.category stops working here. That is why it is a
    # separate migration: between 001c and this one there is a window, however long is
    # needed, to move every reader onto category_id and check that nothing is left behind.
    #
    # All generated by Alembic. It is safe to demand NOT NULL because 001c filled the column
    # for every row; if any product had been inserted without a category since then, this
    # line would fail, and that is the point: the database refuses to keep a half-done state.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema and data."""
    # CORRECTED BY HAND. Autogenerate wrote this first line as nullable=False, and it cannot
    # work: adding a NOT NULL column with no default to a table that already has 36 rows is
    # rejected by PostgreSQL, because there is no value to put in those rows. Autogenerate
    # only compares schemas, so it does not know the table has data, nor where the old text
    # could come from. Undoing a CONTRACT means putting the data back, in three steps.

    # 1. The column comes back empty, so it has to allow NULL for a moment.
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # 2. Refill it by following the foreign key: the name lives in categories.
    op.execute("""
        UPDATE products
        SET category = categories.name
        FROM categories
        WHERE categories.id = products.category_id
    """)

    # 3. Only now, with every row filled, can the rule be put back.
    op.alter_column('products', 'category', existing_type=sa.VARCHAR(length=50), nullable=False)

    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
