"""cart and orders

Revision ID: 002_cart_and_orders
Revises: 001d_categories_contract
Create Date: 2026-09-19 17:03:16.815166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_cart_and_orders'
down_revision: Union[str, Sequence[str], None] = '001d_categories_contract'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ENTIRELY generated by Alembic, and for once there is nothing to add by hand: this
    # migration only creates empty tables, and empty is the correct starting state for a
    # cart and for an order. Compare with 001_products, which needed its seed data written
    # in by hand, and with 001a/001b, which were only data.
    #
    # Read the two item tables side by side, because the difference IS the lesson of this
    # checkpoint: cart_items has no price column and order_items has one. A cart shows
    # today's price, read from products; an order keeps the price it was bought at.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_email', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='paid', nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_cents >= 0', name='ck_orders_total_cents'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('cart_token', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_cart_items_quantity'),
    sa.ForeignKeyConstraint(['cart_token'], ['carts.token'], name='fk_cart_items_cart_token', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_cart_items_product_id'),
    sa.PrimaryKeyConstraint('cart_token', 'product_id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_order_items_order_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_order_items_product_id'),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('orders')
    op.drop_table('carts')
    # ### end Alembic commands ###
