"""addresses

Revision ID: 003a_addresses
Revises: 003_users
Create Date: 2026-09-19 19:08:06.633566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003a_addresses'
down_revision: Union[str, Sequence[str], None] = '003_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # All generated by Alembic; nothing by hand. Worth pointing at in class: the kind of
    # address is the is_billing column, not a row in a table of address types, and the
    # unique constraint on (user_id, is_billing) is what limits each person to one of
    # each. That rule lives in the database, so no amount of clicking can break it.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_billing', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), server_default='ES', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_addresses_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'is_billing', name='uq_addresses_user_is_billing')
    )
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
