"""address history

Revision ID: 003b_address_history
Revises: 003a_addresses
Create Date: 2026-09-19 19:27:42.549147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003b_address_history'
down_revision: Union[str, Sequence[str], None] = '003a_addresses'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # All generated by Alembic, and all of it safe to run while the old code is still
    # serving: the new column has a default so existing rows become active, the new
    # column on orders is nullable so every order already placed stays valid, and the
    # constraint that goes away is one that is being LOOSENED, never tightened.
    #
    # The interesting line is the index. It is unique only WHERE is_active, so a person
    # can keep any number of retired addresses and at most one in use of each kind.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_constraint(op.f('uq_addresses_user_is_billing'), 'addresses', type_='unique')
    op.create_index('uq_addresses_one_active', 'addresses', ['user_id', 'is_billing'], unique=True, postgresql_where=sa.text('is_active'))
    op.add_column('orders', sa.Column('shipping_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_orders_shipping_address_id', 'orders', 'addresses', ['shipping_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema and data."""
    # Generated by Alembic, with one block added BY HAND in the middle, because the
    # generated version cannot run: the schema it goes back to allows only one address
    # per person per kind, and by now people have retired ones as well. Reproduced before
    # fixing: "could not create unique index ... Key (user_id, is_billing) is duplicated".
    op.drop_constraint('fk_orders_shipping_address_id', 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_address_id')
    op.drop_index('uq_addresses_one_active', table_name='addresses', postgresql_where=sa.text('is_active'))

    # ADDED BY HAND. This one really does destroy information, and there is no way round
    # it: the old schema has nowhere to put a history, so the history has to go. Saying so
    # out loud is the point - a downgrade is not always free, and knowing which ones cost
    # something is the reason for writing them before running the upgrade in the first
    # place. The addresses in use are kept; the retired ones are dropped.
    op.execute("DELETE FROM addresses WHERE NOT is_active")

    op.create_unique_constraint(op.f('uq_addresses_user_is_billing'), 'addresses', ['user_id', 'is_billing'], postgresql_nulls_not_distinct=False)
    op.drop_column('addresses', 'is_active')
