"""orders belong to a user

Revision ID: 003c_orders_user
Revises: 003b_address_history
Create Date: 2026-09-19 19:42:09.454235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003c_orders_user'
down_revision: Union[str, Sequence[str], None] = '003b_address_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_foreign_key('fk_orders_user_id', 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

    # PART 2, BY HAND. Two things autogenerate cannot do, for the same reason as always:
    # it compares schemas and knows nothing about the rows already in the table.

    # Give the orders that can be matched an owner. Nothing matches today, because every
    # order so far carries the placeholder address, but this is the shape the backfill
    # takes in a real migration and it is what makes the next step safe when it does.
    op.execute("""
        UPDATE orders
        SET user_id = users.id
        FROM users
        WHERE users.email = orders.customer_email
    """)

    # And now the rule itself: an order belongs to somebody.
    #
    # NOT a NOT NULL column, because the orders placed before this rule existed have no
    # owner and there is nobody to give them to. Making the column NOT NULL would leave
    # two choices, both bad: invent an owner, or delete real orders.
    #
    # NOT VALID is exactly the tool for "from here on". PostgreSQL enforces the check on
    # every row inserted or updated from now on, and does not go back over the rows that
    # are already there. The same trick is how a constraint gets added to a huge table
    # without locking it for the length of a full scan; validating it later, once the old
    # rows have been dealt with, is one line: VALIDATE CONSTRAINT.
    op.execute("""
        ALTER TABLE orders
        ADD CONSTRAINT ck_orders_user_id_required
        CHECK (user_id IS NOT NULL) NOT VALID
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # The constraint has to go before the column it talks about. Nothing to restore here:
    # this migration only ever ADDED, so going back loses only the ownership it recorded.
    op.execute("ALTER TABLE orders DROP CONSTRAINT ck_orders_user_id_required")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_user_id', 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
