"""product price history

Revision ID: 004_price_history
Revises: 003c_orders_user
Create Date: 2026-09-20 00:22:19.418849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004_price_history'
down_revision: Union[str, Sequence[str], None] = '003c_orders_user'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nothing was added by hand here, and that is worth a line because it has only happened
    # once before in this project (002, the cart). The reason is the same both times: this
    # migration only creates an EMPTY table. Autogenerate needs help whenever a migration
    # has to say something about rows that already exist, and here there are none - a price
    # history that starts empty is not a gap, it is the truth about what we know so far.
    #
    # The foreign key carries its name from the model, so the downgrade knows what to drop.
    # That is the fix for the warning that 001c earned the hard way.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_price_history',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('previous_price_cents', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_price_history_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_price_history_product', 'product_price_history', ['product_id', 'changed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_price_history_product', table_name='product_price_history')
    op.drop_table('product_price_history')
    # ### end Alembic commands ###
