"""payment intent

Revision ID: 005_payment
Revises: 004a_price_trigger
Create Date: 2026-09-21 00:18:56.233559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005_payment'
down_revision: Union[str, Sequence[str], None] = '004a_price_trigger'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # One column, and nothing was added by hand - the third time that has happened in this
    # project, after 002 and 004. The reason is the same every time: this migration says
    # nothing about the rows that already exist. Orders placed before there was a gateway
    # have no payment, and NULL is the honest word for that, not a gap to be filled in.
    #
    # What this migration does NOT contain is the interesting part. The phase it belongs to
    # charges the card INSIDE the same transaction that creates the order, so an order is
    # either paid or never existed, and `status` can keep defaulting to "paid" - for the
    # first time truthfully. The day the charge stops being part of that transaction, this
    # table needs a state that means neither, and that migration is a different one.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_intent_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_intent_id')
    # ### end Alembic commands ###
