"""checkout session

Revision ID: 006_checkout
Revises: 005_payment
Create Date: 2026-09-25 06:33:51.739789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006_checkout'
down_revision: Union[str, Sequence[str], None] = '005_payment'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The second line is the one that matters, and it is here only because of a decision
    # made in the previous objective. Changing a server default is invisible to
    # --autogenerate unless env.py passes compare_server_default=True; that option was
    # switched on in 005 after this exact edit produced an EMPTY migration and the drift
    # test stayed green. This is the first time it pays for itself.
    #
    # And the word being changed is the same one phase 0 caught lying. It has now moved
    # three times: "paid" while nobody paid, "paid" and finally true when the charge lived
    # inside this transaction, and "pending_payment" from here on - because a buyer typing
    # their card on Stripe's page has an order that exists and is not paid.
    #
    # Nothing backfills the rows that already exist: every order in the table was created
    # under the old rule and IS paid. Deciding what to do with them is the next objective's
    # job, and doing it here by accident would be the worst way to answer it.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('checkout_session_id', sa.String(length=100), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default='pending_payment',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'paid'::character varying"),
               existing_nullable=False)
    op.drop_column('orders', 'checkout_session_id')
    # ### end Alembic commands ###
